# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Qtself.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ui.Ui_WindowsDevicePortal import Ui_WindowsDevicePortal
from lib.WindowsDevicePortal import WindowsDevicePortal


class QtWindowsDevicePortal(QtWidgets.QWidget):
    
    
    def __init__(self, parent=None):
        
        QtWidgets.QWidget.__init__(self, parent)
        
        WindowsDevicePortal().interface(self)
        
        self.ui = Ui_WindowsDevicePortal()
        self.ui.setupUi(self)
    
        self.ui.batteryTimer = QtCore.QTimer()
        self.ui.batteryTimer.timeout.connect(self.updateBattery)
        self.ui.batteryTimer.start(2000)


    def _disableInputs(self, b):
        
        self.ui.connectButton.setDisabled(b)
        self.ui.hostInput.setDisabled(b)
        self.ui.loginInput.setDisabled(b)
        self.ui.passwordInput.setDisabled(b)


    def updateBattery(self):
        
        b = self.getBattery()
        self.ui.batteryLevel.setText(b)
        
        if not self.isConnected():
            self._disableInputs(False)


    def setupConnection(self):
        
        host = self.ui.hostInput.text()
        login = self.ui.loginInput.text()
        password = self.ui.passwordInput.text()
        
        self.connect(host, auth=(login, password), certfile="resources/holocert")
        
        if self.isConnected():
            self._disableInputs(True)


    @staticmethod
    def test(config):
        
        import sys
        
        app = QtWidgets.QApplication(sys.argv)
        wdp = QtWindowsDevicePortal()
        
        wdp.ui.hostInput.setText(config["host"])
        wdp.ui.loginInput.setText(config["auth"][0])
        wdp.ui.passwordInput.setText(config["auth"][1])
        
        wdp.show()
        sys.exit(app.exec_())
